export const REGISTER_USER = 'REGISTER_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT = 'LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'
// export const REGISTER_USER = 'REGISTER_USER'
// export const REGISTER_USER = 'REGISTER_USER'
// export const REGISTER_USER = 'REGISTER_USER'